server:
  port: 8020

spring:
  datasource:
    url: jdbc:mysql://yamabiko.proxy.rlwy.net:22913/railway
    username: root
    password: NezcAZMsCYadNkSXxVcBdYCzhkHJvzfn
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: thophan357@gmail.com
    password: ubsygfyidbcygsye
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

api:
  prefix: api/v1/gmshop

cloudinary:
  cloud_name: df40lpss5
  api_key: 423287891566818
  api_secret: bveeThgQEwJjVZB7FL7eTP-R53Q

jwt:
  expiration: 86400
  secretkey: 5+2eqXSVC4XDqxgu2rHXDRSGbRUgCfk9uuTKjoIw1N8=
