
server:
  port: 8020


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver

    username: root
    password:
    jpa:
      show_sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: thophan357@gmail.com
    password: ubsygfyidbcygsye
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

api:
  prefix: api/v1/gmshop



jwt:
  expiration: 86400
  secretkey: 5+2eqXSVC4XDqxgu2rHXDRSGbRUgCfk9uuTKjoIw1N8=




